import type { HomeAssistant } from './types';

const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    card_name: 'Checklist Card',
    card_description: 'Check entity states and quickly fix any issues.',
    title: 'Checklist',
    status: 'Status',
    entity: 'Entity',
    all_good: 'All good!',
    problems_found: 'Found {count} problems',
    fix_all: 'Fix All',
    fix: 'Fix',
    ok: 'OK',
    show: 'Show',
    hide: 'Hide',
    show_ok_items_btn: 'Show {count} OK items',
    hide_ok_items_btn: 'Hide {count} OK items',
    unavailable: 'Unavailable',
    required: 'Required',
    attribute: 'Attribute',
    not_exists: 'Not exists',
    current_state: 'Current state',
    accepted_one_of: 'Accepted one of',
    fix_target: 'Fix target',
    config_error: 'Invalid configuration',
    expected_pattern_error: 'Error parsing expected pattern',
    fix_process_error: 'Error in entity fix process',
    editor_title: 'Title',
    layout_section: 'Card Layout',
    appearance_section: 'Appearance',
    sorting_section: 'Sorting',
    display_section: 'Display',
    layout_dir: 'Item arrangement',
    layout_col: 'Columns (vertical list)',
    layout_row: 'Rows (horizontal scroll)',
    max_items_col: 'Number of columns',
    max_items_row: 'Items per column',
    layout_cols_hint: 'The card will be displayed in a larger width automatically.',
    layout_rows_hint: 'Items scroll horizontally across the card',
    layout_dir_helper: 'Vertical list or horizontal scroll',
    count_helper_col: 'Number of columns to spread items across',
    count_helper_row: 'Items per row before scrolling',
    sort_direction: 'Sort direction',
    sort_asc: 'Ascending',
    sort_desc: 'Descending',
    text_mode_helper: 'Long item names scroll horizontally instead of being clipped',
    show_ok_helper: 'Choose how valid items will be displayed',
    entities_section: 'Entities to check',
    check_num: 'Check ',
    remove: 'Remove',
    select_entity: 'Select Entity',
    display_name: 'Display Name (Optional)',
    check_condition: 'Check condition',
    cond_any: 'At least one condition is OK (OR)',
    cond_all: 'All conditions must be OK (AND)',
    ok_state: 'OK State',
    default_fix: 'Default to fix',
    default_fix_star: 'Default to fix',
    remove_state: 'Remove State',
    attr_check: 'Attribute to check (Optional)',
    no_attr: '-- No attribute --',
    attr_val: 'OK value for attribute',
    custom_fix: 'Custom fix service (Optional)',
    custom_fix_hint: 'Example: {"service": "light.turn_on"}',
    prereq_entity: 'Prerequisite entity (Optional)',
    prereq_state: 'Prerequisite state',
    prereq_hint: 'Comma-separated OR, uses != for negation (e.g. !=off)',
    add_state: '+ Add another OK state',
    not_selected: 'Not selected',
    every: 'All',
    one_of: 'One of',
    add_check: '+ Add new check',
    loading: 'Loading Home Assistant editor components...',
    drag_here: 'Drop here',
    sort_mode: 'Sort by',
    sort_manual: 'Manual (drag & drop)',
    sort_status: 'Problem status (Problems first)',
    sort_alphabetical: 'Alphabetical',
    sort_domain: 'Domain',
    sort_severity: 'Severity',
    sort_last_changed: 'Last changed',
    group_by: 'Group by',
    group_none: 'None',
    group_severity: 'Severity',
    group_domain: 'Domain',
    group_area: 'Area',
    show_ok_section: 'Show OK entities',
    show_ok_inline: 'Inline (Mixed with problems)',
    show_ok_collapsed: 'Collapsed Section',
    show_ok_hidden: 'Hidden completely',
    severity: 'Severity',
    severity_info: 'Info',
    severity_warning: 'Warning',
    severity_critical: 'Critical',
    icon_override: 'Custom Icon (e.g., mdi:alert)',
    color_override: 'Custom Color',
    confirm_fix: 'Are you sure you want to fix {name}?',
    advanced_settings: 'Advanced Settings',
    status_problem: 'Problem',
    status_ok: 'OK',
    cancel: 'Cancel',
    snooze: 'Snooze',
    snooze_dialog_title: 'Snooze check',
    snooze_dialog_desc: 'Ignore this check for:',
    snooze_1h: '1 hour',
    snooze_2h: '2 hours',
    snooze_4h: '4 hours',
    snooze_8h: '8 hours',
    snooze_24h: '1 day',
    snooze_3d: '3 days',
    snooze_custom_placeholder: 'Custom hours...',
    snooze_confirm_btn: 'Snooze',
    unsnooze: 'Unsnooze',
    snoozed_section_show: 'Show {count} snoozed items',
    snoozed_section_hide: 'Hide {count} snoozed items',
    snoozed_until: 'Snoozed until {time}',
    text_mode_label: 'Long text behavior',
    text_mode_clip: 'Clip',
    text_mode_scroll: 'Auto-scroll',
  },

  he: {
    card_name: 'כרטיס בדיקות',
    card_description: 'בדיקת מצב ישויות ותיקון מהיר של תקלות.',
    title: 'בדיקות',
    status: 'מצב',
    entity: 'ישות',
    all_good: 'הכל תקין!',
    problems_found: 'נמצאו {count} תקלות',
    fix_all: 'תיקון הכל',
    fix: 'תיקון',
    ok: 'תקין',
    show: 'הצג',
    hide: 'הסתר',
    show_ok_items_btn: 'הצג {count} פריטים תקינים',
    hide_ok_items_btn: 'הסתר {count} פריטים תקינים',
    unavailable: 'לא זמין',
    required: 'נדרש',
    attribute: 'תכונה',
    not_exists: 'לא קיים',
    current_state: 'מצב נוכחי',
    accepted_one_of: 'מקובל אחד מ',
    fix_target: 'יעד לתיקון',
    config_error: 'תצורה לא תקינה',
    expected_pattern_error: 'שגיאה בפענוח התבנית הצפויה',
    fix_process_error: 'שגיאה בתהליך תיקון הישות',
    editor_title: 'כותרת',
    layout_section: 'פריסת הכרטיס',
    appearance_section: 'מראה',
    sorting_section: 'מיון',
    display_section: 'תצוגה',
    layout_dir: 'סידור פריטים',
    layout_col: 'עמודות (רשימה אנכית)',
    layout_row: 'שורות (גלילה אופקית)',
    max_items_col: 'מספר עמודות',
    max_items_row: 'פריטים בעמודה',
    layout_cols_hint: 'הכרטיס יוצג ברוחב גדול יותר אוטומטית',
    layout_rows_hint: 'הפריטים נגללים אופקית לאורך הכרטיס',
    layout_dir_helper: 'רשימה אנכית או גלילה אופקית',
    count_helper_col: 'מספר העמודות שעליהן יתפרסו הפריטים',
    count_helper_row: 'פריטים בשורה לפני גלילה',
    sort_direction: 'כיוון מיון',
    sort_asc: 'עולה',
    sort_desc: 'יורד',
    text_mode_helper: 'שמות פריטים ארוכים ייגללו אופקית במקום להיחתך',
    show_ok_helper: 'בחר כיצד יוצגו פריטים תקינים',
    entities_section: 'רשימת הישויות לבדיקה',
    check_num: 'בדיקה ',
    remove: 'הסר',
    select_entity: 'בחר ישות',
    display_name: 'שם תצוגה (אופציונלי)',
    check_condition: 'תנאי הבדיקה',
    cond_any: 'מספיק שאחד מהמצבים תקין (OR)',
    cond_all: 'כל המצבים חייבים להיות תקינים (AND)',
    ok_state: 'מצב תקין',
    default_fix: 'ברירת מחדל לתיקון',
    default_fix_star: 'ברירת מחדל לתיקון',
    remove_state: 'הסר מצב',
    attr_check: 'תכונה לבדיקה (אופציונלי)',
    no_attr: '-- ללא תכונה --',
    attr_val: 'ערך תקין לתכונה',
    custom_fix: 'שירות תיקון ייעודי (אופציונלי)',
    custom_fix_hint: 'דוגמה: {"service": "light.turn_on"}',
    prereq_entity: 'ישות תנאי מוקדם (אופציונלי)',
    prereq_state: 'מצב נדרש',
    prereq_hint: 'הפרדה בפסיקים מהווה OR, שימוש ב-!= לשלילה (למשל: !=off)',
    add_state: '+ הוסף מצב תקין נוסף',
    not_selected: 'לא נבחרה',
    every: 'כל',
    one_of: 'אחד מ',
    add_check: '+ הוספת בדיקה חדשה',
    loading: 'טעינת רכיבי עריכה של Home Assistant...',
    drag_here: 'שחרר כאן',
    sort_mode: 'מיון לפי',
    sort_manual: 'ידני (גרירה)',
    sort_status: 'מצב (תקלות למעלה)',
    sort_alphabetical: 'אלפביתי',
    sort_domain: 'סוג ישות',
    sort_severity: 'חומרה',
    sort_last_changed: 'שינוי אחרון',
    group_by: 'קיבוץ לפי',
    group_none: 'ללא קיבוץ',
    group_severity: 'חומרה',
    group_domain: 'סוג ישות',
    group_area: 'אזור',
    show_ok_section: 'הצגת ישויות תקינות',
    show_ok_inline: 'ברשימה (מעורבב עם תקלות)',
    show_ok_collapsed: 'באזור מוסתר (נפתח בלחיצה)',
    show_ok_hidden: 'מוסתר לחלוטין',
    severity: 'חומרה',
    severity_info: 'מידע',
    severity_warning: 'אזהרה',
    severity_critical: 'קריטי',
    icon_override: 'אייקון מותאם (למשל mdi:alert)',
    color_override: 'צבע מותאם',
    confirm_fix: 'האם לתקן את {name}?',
    advanced_settings: 'הגדרות מתקדמות',
    status_problem: 'תקלה',
    status_ok: 'תקין',
    cancel: 'ביטול',
    snooze: 'דחה',
    snooze_dialog_title: 'דחיית בדיקה',
    snooze_dialog_desc: 'להתעלם מבדיקה זו למשך:',
    snooze_1h: 'שעה',
    snooze_2h: 'שעתיים',
    snooze_4h: '4 שעות',
    snooze_8h: '8 שעות',
    snooze_24h: 'יום',
    snooze_3d: '3 ימים',
    snooze_custom_placeholder: 'שעות מותאמות...',
    snooze_confirm_btn: 'דחה',
    unsnooze: 'בטל דחייה',
    snoozed_section_show: 'הצגת {count} פריטים דחויים',
    snoozed_section_hide: 'הסתרת {count} פריטים דחויים',
    snoozed_until: 'נדחה עד {time}',
    text_mode_label: 'טיפול בטקסט ארוך',
    text_mode_clip: 'חיתוך',
    text_mode_scroll: 'גלילה אוטומטית',
  },
};

export function localize(
  hass: HomeAssistant | undefined,
  key: string,
  params?: Record<string, string | number>
): string {
  return _translate(hass?.language ?? 'en', key, params);
}

// Uses navigator.language for static contexts (card registration, getStubConfig)
// that run before hass is injected.
export function localizeStatic(key: string): string {
  const lang = (typeof navigator !== 'undefined' ? navigator.language : 'en')
    .split('-')[0]
    .toLowerCase();
  return _translate(lang, key);
}

function _translate(
  lang: string,
  key: string,
  params?: Record<string, string | number>
): string {
  const selectedLang = lang in TRANSLATIONS ? lang : 'en';
  let str = TRANSLATIONS[selectedLang][key] ?? TRANSLATIONS['en'][key] ?? key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      str = str.replace(`{${k}}`, String(v));
    }
  }
  return str;
}
