import type { HomeAssistant } from './types';

const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Card
    card_name: 'Checklist Card',
    card_description: 'Check entity states and quickly fix any issues.',
    title: 'Checklist',
    status: 'Status',
    all_good: 'All good!',
    problems_found: 'Found {count} problems',
    problems_found_one: 'Found 1 problem',
    fix_all: 'Fix all',
    fix: 'Fix',
    ok: 'OK',
    show_ok_items_btn: 'Show {count} OK items',
    show_ok_items_btn_one: 'Show 1 OK item',
    hide_ok_items_btn: 'Hide {count} OK items',
    hide_ok_items_btn_one: 'Hide 1 OK item',
    unavailable: 'Unavailable',
    required: 'Required',
    attribute: 'Attribute',
    not_exists: 'Missing',
    current_state: 'Current state',
    accepted_one_of: 'Accepted',
    fix_target: 'Fix target',
    config_error: 'Invalid configuration: "checks" must be a list',
    fix_process_error: 'Could not fix the entity',
    status_problem: 'Problem',
    status_ok: 'OK',
    cancel: 'Cancel',
    dismiss: 'Dismiss',
    confirm_title: 'Confirm fix',
    confirm_fix: 'Fix {name}?',
    confirm_fix_all: 'Fix all {count} problems?',
    snooze: 'Snoozed',
    snooze_dialog_title: 'Snooze check',
    snooze_dialog_desc: 'Ignore this check for:',
    snooze_1h: '1 hour',
    snooze_2h: '2 hours',
    snooze_4h: '4 hours',
    snooze_8h: '8 hours',
    snooze_24h: '1 day',
    snooze_3d: '3 days',
    snooze_custom_label: 'Custom duration (hours)',
    snooze_custom_placeholder: 'For example: 1.5',
    snooze_confirm_btn: 'Snooze',
    unsnooze: 'Unsnooze',
    snoozed_section_show: 'Show {count} snoozed items',
    snoozed_section_show_one: 'Show 1 snoozed item',
    snoozed_section_hide: 'Hide {count} snoozed items',
    snoozed_section_hide_one: 'Hide 1 snoozed item',
    snoozed_until: 'Snoozed until {time}',

    // Editor: card settings
    loading: 'Loading Home Assistant editor components…',
    editor_title: 'Title',
    appearance_section: 'Appearance',
    sorting_section: 'Sorting',
    display_section: 'Display',
    layout_dir: 'Item arrangement',
    layout_dir_helper: 'Vertical list or horizontal scroll',
    layout_col: 'Columns (vertical list)',
    layout_row: 'Rows (horizontal scroll)',
    max_items_col: 'Number of columns',
    max_items_row: 'Items per column',
    count_helper_col: 'Number of columns to spread items across',
    count_helper_row: 'Items stacked in each column before scrolling sideways',
    text_mode_label: 'Long text',
    text_mode_helper: 'Scroll long names horizontally instead of cutting them off',
    text_mode_clip: 'Clip',
    text_mode_scroll: 'Auto-scroll',
    sort_mode: 'Sort by',
    sort_manual: 'Manual',
    sort_status: 'Status (problems first)',
    sort_alphabetical: 'Alphabetical',
    sort_domain: 'Domain',
    sort_severity: 'Severity',
    sort_last_changed: 'Last changed',
    sort_direction: 'Sort direction',
    sort_asc: 'Ascending',
    sort_desc: 'Descending',
    show_ok_section: 'OK items',
    show_ok_helper: 'How to show items that are OK',
    show_ok_inline: 'In the list, mixed with problems',
    show_ok_collapsed: 'In a collapsed section',
    show_ok_hidden: 'Hidden (the card hides itself when everything is OK)',

    // Editor: checks
    entities_section: 'Checks',
    no_checks_yet: 'No checks yet. Add one to get started.',
    add_check: 'Add check',
    paste_check: 'Paste check',
    move_before: 'Move check before',
    move_after: 'Move check after',
    duplicate: 'Duplicate check',
    cut_check: 'Cut check',
    remove: 'Delete check',
    show_code_editor: 'Show code editor',
    show_visual_editor: 'Show visual editor',
    yaml_hint_json: 'JSON syntax, applied after a short pause.',
    select_entity: 'Entity',
    display_name: 'Name',
    display_name_helper: 'Leave empty to use the entity name',
    check_condition: 'OK when',
    cond_any: 'Any condition is met (OR)',
    cond_all: 'All conditions are met (AND)',
    default_fix: 'Condition used by Fix',
    default_fix_helper: 'Fix sets the entity to this condition',
    condition_n: 'Condition {n}',
    condition_single: 'OK condition',
    remove_state: 'Delete condition',
    add_state: 'Add condition',
    advanced_settings: 'Advanced',
    severity: 'Severity',
    severity_helper: 'Sets the order for Fix all and for sorting by severity',
    severity_info: 'Info',
    severity_warning: 'Warning',
    severity_critical: 'Critical',
    icon_override: 'Icon',
    color_override: 'Name color',
    color_helper: 'Any CSS color, for example #1976d2 or var(--accent-color)',
    show_last_changed: 'Show time since last change',
    confirmation: 'Ask for confirmation before fixing',
    interactions_section: 'Interactions',
    tap_action: 'Tap behavior',
    hold_action: 'Hold behavior',
    hold_action_helper: 'Default: open the snooze dialog',
    double_tap_action: 'Double tap behavior',
    double_tap_action_helper: 'Default: snooze a problem',
    ok_state: 'OK state',
    ok_state_helper: 'You can also enter states(\'entity_id\') to compare with another entity',
    attr_check: 'Attribute (optional)',
    attr_val: 'OK attribute value',
    custom_fix: 'Custom fix action (optional)',
    custom_fix_hint: 'domain.action, or JSON: {"perform_action": "light.turn_on", "data": {"brightness_pct": 50}}',
    prereq_section: 'Only check when',
    prereq_entity: 'Prerequisite entity',
    prereq_state: 'Prerequisite state',
    prereq_hint: 'Separate values with commas for OR; prefix with != to negate (for example !=off)',
  },

  he: {
    // כרטיס
    card_name: 'כרטיס בדיקות',
    card_description: 'בדיקת מצב ישויות ותיקון מהיר של תקלות.',
    title: 'בדיקות',
    status: 'מצב',
    all_good: 'הכול תקין!',
    problems_found: 'נמצאו {count} תקלות',
    problems_found_one: 'נמצאה תקלה אחת',
    fix_all: 'לתקן הכול',
    fix: 'תיקון',
    ok: 'תקין',
    show_ok_items_btn: 'הצגת {count} תקינים',
    show_ok_items_btn_one: 'הצגת פריט תקין אחד',
    hide_ok_items_btn: 'הסתרת {count} תקינים',
    hide_ok_items_btn_one: 'הסתרת פריט תקין אחד',
    unavailable: 'לא זמין',
    required: 'נדרש',
    attribute: 'מאפיין',
    not_exists: 'חסר',
    current_state: 'מצב נוכחי',
    accepted_one_of: 'מצבים תקינים',
    fix_target: 'יעד התיקון',
    config_error: 'הגדרה לא תקינה: "checks" חייב להיות רשימה',
    fix_process_error: 'לא הצלחנו לתקן את הישות',
    status_problem: 'תקלה',
    status_ok: 'תקין',
    cancel: 'ביטול',
    dismiss: 'סגירה',
    confirm_title: 'אישור תיקון',
    confirm_fix: 'לתקן את {name}?',
    confirm_fix_all: 'לתקן את כל {count} התקלות?',
    snooze: 'נדחה',
    snooze_dialog_title: 'דחיית בדיקה',
    snooze_dialog_desc: 'להתעלם מהבדיקה הזו למשך:',
    snooze_1h: 'שעה',
    snooze_2h: 'שעתיים',
    snooze_4h: '4 שעות',
    snooze_8h: '8 שעות',
    snooze_24h: 'יום',
    snooze_3d: '3 ימים',
    snooze_custom_label: 'משך אחר (בשעות)',
    snooze_custom_placeholder: 'לדוגמה: 1.5',
    snooze_confirm_btn: 'דחייה',
    unsnooze: 'ביטול דחייה',
    snoozed_section_show: 'הצגת {count} דחויים',
    snoozed_section_show_one: 'הצגת פריט דחוי אחד',
    snoozed_section_hide: 'הסתרת {count} דחויים',
    snoozed_section_hide_one: 'הסתרת פריט דחוי אחד',
    snoozed_until: 'נדחה עד {time}',

    // עורך: הגדרות כרטיס
    loading: 'טוען את רכיבי העריכה של Home Assistant…',
    editor_title: 'כותרת',
    appearance_section: 'מראה',
    sorting_section: 'מיון',
    display_section: 'תצוגה',
    layout_dir: 'סידור הפריטים',
    layout_dir_helper: 'רשימה אנכית או גלילה אופקית',
    layout_col: 'עמודות (רשימה אנכית)',
    layout_row: 'שורות (גלילה אופקית)',
    max_items_col: 'מספר עמודות',
    max_items_row: 'פריטים בעמודה',
    count_helper_col: 'על כמה עמודות לפרוס את הפריטים',
    count_helper_row: 'כמה פריטים בכל עמודה לפני גלילה הצידה',
    text_mode_label: 'טקסט ארוך',
    text_mode_helper: 'שמות ארוכים ייגללו לרוחב במקום להיחתך',
    text_mode_clip: 'חיתוך',
    text_mode_scroll: 'גלילה אוטומטית',
    sort_mode: 'מיון לפי',
    sort_manual: 'ידני',
    sort_status: 'מצב (תקלות קודם)',
    sort_alphabetical: 'א״ב',
    sort_domain: 'סוג ישות',
    sort_severity: 'חומרה',
    sort_last_changed: 'שינוי אחרון',
    sort_direction: 'כיוון המיון',
    sort_asc: 'עולה',
    sort_desc: 'יורד',
    show_ok_section: 'פריטים תקינים',
    show_ok_helper: 'איך להציג פריטים שהם תקינים',
    show_ok_inline: 'ברשימה, יחד עם התקלות',
    show_ok_collapsed: 'באזור מקופל',
    show_ok_hidden: 'מוסתרים (הכרטיס נעלם כשהכול תקין)',

    // עורך: בדיקות
    entities_section: 'בדיקות',
    no_checks_yet: 'עדיין אין בדיקות. אפשר להוסיף בדיקה ראשונה.',
    add_check: 'הוספת בדיקה',
    paste_check: 'הדבקת בדיקה',
    move_before: 'הזזה אחורה',
    move_after: 'הזזה קדימה',
    duplicate: 'שכפול בדיקה',
    cut_check: 'גזירת בדיקה',
    remove: 'מחיקת בדיקה',
    show_code_editor: 'עורך קוד',
    show_visual_editor: 'עורך חזותי',
    yaml_hint_json: 'תחביר JSON, נשמר אחרי הפסקה קצרה בהקלדה.',
    select_entity: 'ישות',
    display_name: 'שם',
    display_name_helper: 'ריק = שם הישות',
    check_condition: 'תקין כאשר',
    cond_any: 'אחד התנאים מתקיים (OR)',
    cond_all: 'כל התנאים מתקיימים (AND)',
    default_fix: 'התנאי שהתיקון יחיל',
    default_fix_helper: 'לחיצה על "תיקון" תעביר את הישות למצב הזה',
    condition_n: 'תנאי {n}',
    condition_single: 'תנאי תקינות',
    remove_state: 'מחיקת תנאי',
    add_state: 'הוספת תנאי',
    advanced_settings: 'מתקדם',
    severity: 'חומרה',
    severity_helper: 'קובעת את סדר התיקון ב"לתקן הכול" ובמיון לפי חומרה',
    severity_info: 'מידע',
    severity_warning: 'אזהרה',
    severity_critical: 'קריטי',
    icon_override: 'סמל',
    color_override: 'צבע השם',
    color_helper: 'כל צבע CSS, למשל ‎#1976d2 או var(--accent-color)',
    show_last_changed: 'הצגת הזמן מאז השינוי האחרון',
    confirmation: 'לבקש אישור לפני תיקון',
    interactions_section: 'אינטראקציות',
    tap_action: 'פעולה בהקשה',
    hold_action: 'פעולה בלחיצה ארוכה',
    hold_action_helper: 'ברירת מחדל: חלון הדחייה',
    double_tap_action: 'פעולה בהקשה כפולה',
    double_tap_action_helper: 'ברירת מחדל: דחיית תקלה',
    ok_state: 'מצב תקין',
    ok_state_helper: 'אפשר גם להזין states(\'entity_id\') כדי להשוות לישות אחרת',
    attr_check: 'מאפיין (לא חובה)',
    attr_val: 'ערך תקין למאפיין',
    custom_fix: 'פעולת תיקון מותאמת (לא חובה)',
    custom_fix_hint: 'domain.action, או JSON: {"perform_action": "light.turn_on", "data": {"brightness_pct": 50}}',
    prereq_section: 'לבדוק רק כאשר',
    prereq_entity: 'ישות תנאי',
    prereq_state: 'מצב נדרש',
    prereq_hint: 'פסיק בין ערכים = OR; ‏!= בהתחלה = שלילה (למשל ‎!=off)',
  },
};

export function localize(
  hass: HomeAssistant | undefined,
  key: string,
  params?: Record<string, string | number>
): string {
  return _translate(hass?.language ?? 'en', key, params);
}

// Uses navigator.language for static contexts (card registration, getStubConfig)
// that run before hass is injected.
export function localizeStatic(key: string): string {
  const lang = (typeof navigator !== 'undefined' ? navigator.language : 'en')
    .split('-')[0]
    .toLowerCase();
  return _translate(lang, key);
}

function _translate(
  lang: string,
  key: string,
  params?: Record<string, string | number>
): string {
  const selectedLang = lang in TRANSLATIONS ? lang : 'en';
  // Singular form: `<key>_one` is used when count is 1 and the language defines it.
  const singular = params?.count === 1 ? TRANSLATIONS[selectedLang][`${key}_one`] : undefined;
  let str = singular ?? TRANSLATIONS[selectedLang][key] ?? TRANSLATIONS['en'][key] ?? key;

  if (params) {
    for (const [k, v] of Object.entries(params)) {
      str = str.replaceAll(`{${k}}`, String(v));
    }
  }
  return str;
}
